﻿version: '3.9'
services:
  webapp:
    build: .
    image: net9asp:latest
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Str0ngP@ssw0rd!
      - MSSQL_PID=Express
    ports: 
      - "1433:1433"
    restart: on-failure